FROM mcr.microsoft.com/powershell:latest

RUN pwsh -NoProfile -Command \
  Install-Module -name "MicrosoftTeams" -version 1.1.3-preview
  Install-Module -name "Mediant"  
  Install-Module -name "TeamsTools"
